export const NATIONALITIES = {
    AU: 'AU',
    BR: 'BR',
    CA: 'CA',
    CH: 'CH',
    DE: 'DE',
    DK: 'DK',
    ES: 'ES',
    FI: 'FI',
    FR: 'FR',
    GB: 'GB',
    IE: 'IE',
    IR: 'IR',
    NO: 'NO',
    NL: 'NL',
    NZ: 'NZ',
    TR: 'TR',
    US: 'US',
}

export const NATIONALITIES_HUMAN_NAME = {
    [NATIONALITIES.AU]: 'Australia',
    [NATIONALITIES.BR]: 'Brazil',
    [NATIONALITIES.CA]: 'Canada',
    [NATIONALITIES.CH]: 'Switzerland',
    [NATIONALITIES.DE]: 'Germany',
    [NATIONALITIES.DK]: 'Denmark',
    [NATIONALITIES.ES]: 'Spain',
    [NATIONALITIES.FI]: 'Finland',
    [NATIONALITIES.FR]: 'France',
    [NATIONALITIES.GB]: 'United Kingdom',
    [NATIONALITIES.IE]: 'Ireland',
    [NATIONALITIES.IR]: 'Iran',
    [NATIONALITIES.NO]: 'Norway',
    [NATIONALITIES.NL]: 'Netherlands',
    [NATIONALITIES.NZ]: 'New Zealand',
    [NATIONALITIES.TR]: 'Turkey',
    [NATIONALITIES.US]: 'United States',
}
